# Generated by Django 4.2.2 on 2023-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_appuser_ciudad_alter_appuser_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
