# Generated by Django 4.2.2 on 2023-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_name_appuser_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
    ]
